version: '3.8'
services:
  image-splitter:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
      node --max-old-space-size=4096 /app/app/image-splitter.js
    environment:
      - ENV_ID=prod
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - 8800:8800
    volumes:
      - ./tmp:/app/tmp
    restart: always
    network_mode: host
