services:
  image-splitter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV_ID=testing
      - NODE_OPTIONS=--max-old-space-size=4096
    tty: true
    ports:
      - 8800:8800
    # mount folders to keep hot reload
    # while having node_modules installed in the container as it has linux dependencies
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations
      - ./schema.graphql:/app/schema.graphql
      - ./src:/app/src
      - ./tmp:/app/tmp
    restart: always
    depends_on:
      - mysql-test

  mysql-test:
    image: mysql:8.2
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx --sort_buffer_size=512K
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: image-splitter,logs # Create both databases
    mem_limit: 1G
    ports:
      - 5101:3306
    volumes:
      - ./test/mysql82:/var/lib/mysql
      - ./test/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Mount init script

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin
    command: server /data --console-address :9001
    volumes:
      - ./test/minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  create-bucket:
    image: minio/mc:latest
    container_name: create-minio-bucket
    environment:
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: minio-admin
      MINIO_SECRET_KEY: minio-admin
    entrypoint: ["sh", "-c"]
    command: "mc mb gratheon-test || true"
volumes:
  mysql82:
