FROM platformatic/node-caged:25-slim

WORKDIR /app

EXPOSE 8800

COPY package*.json /app/
COPY schema.graphql /app/schema.graphql

COPY src /app/src
COPY migrations /app/migrations
COPY config /app/config

# we have linux dependencies so need to install them in the container
RUN npm install --legacy-peer-deps
RUN npm run build

CMD node --max-old-space-size=4096 ./app/image-splitter.js