services:
  image-splitter:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV_ID=dev
      - NODE_OPTIONS=--max-old-space-size=4096
    tty: true
    ports:
      - 8800:8800
    # mount folders to keep hot reload
    # while having node_modules installed in the container as it has linux dependencies
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations
      - ./schema.graphql:/app/schema.graphql
      - ./src:/app/src
      - ./tmp:/app/tmp
    restart: always

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin
      MINIO_ACCESS_KEY: minio-admin
      MINIO_SECRET_KEY: minio-admin
    command: server /data --console-address :9001
    volumes:
      - ./minio:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  create-bucket:
    image: minio/mc:latest
    container_name: create-minio-bucket-dev
    environment:
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: minio-admin
      MINIO_SECRET_KEY: minio-admin
    entrypoint: ["sh", "-c"]
    command: mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && mc mb gratheon-test || true
    depends_on:
      - minio