version: '3.8'
services:
  image-splitter:
    build:
      dockerfile: Dockerfile.prod
    command:
      node /app/app/image-splitter.js
    environment:
      - ENV_ID=prod
    ports:
      - 8800:8800
    volumes:
      - .:/app/
    restart: always
    network_mode: host
