version: '3.8'
services:
  image-splitter:
    build: .
    command:
      node /app/app/image-splitter.js
    environment:
      - ENV_ID=prod
    ports:
      - 17000:17000
    volumes:
      - .:/app/
    restart: always
    network_mode: host
