#version: '3.9'
services:
  image-splitter:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV_ID=dev
      - DD_ENV=dev
      - DD_PROFILING_ENABLED=true
      - NODE_OPTIONS=--max-old-space-size=4096
    tty: true
    ports:
      - 8800:8800
    # mount folders to keep hot reload
    # while having node_modules installed in the container as it has linux dependencies
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations
      - ./schema.graphql:/app/schema.graphql
      - ./src:/app/src
      - ./tmp:/app/tmp
    restart: always
