/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: M2vWbDDrhRUeksGJM2+8ejiQgHkEIxE3REC1cUwpjJNnxBOtGHUiUUnGH1ydryqNI1YydwJH2yG3cXGAd0Ccrw==
 */

/* eslint-disable */
// tslint:disable

interface DbMigrations {
  executionTime: ((string | Date)) | null
  filename: (string) | null
  hash: (string) | null
}
export default DbMigrations;

interface DbMigrations_InsertParameters {
  executionTime?: ((string | Date)) | null
  filename?: (string) | null
  hash?: (string) | null
}
export type {DbMigrations_InsertParameters}
