/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: rbSaIU/oYNfXat3d5Onxe28GBSMDmc8namuby4qkEFnwL2hpjx8G1erISFPd5PynyNSR3l4Rag8bPShcqc72Ow==
 */

/* eslint-disable */
// tslint:disable

interface FilesFrameSideRel {
  added_time: ((string | Date)) | null
  detectedBees: (unknown) | null
  file_id: number
  frame_side_id: number
  process_end_time: ((string | Date)) | null
  process_start_time: ((string | Date)) | null
  strokeHistory: (unknown) | null
  user_id: number
}
export default FilesFrameSideRel;

interface FilesFrameSideRel_InsertParameters {
  added_time?: ((string | Date)) | null
  detectedBees?: (unknown) | null
  file_id: number
  frame_side_id: number
  process_end_time?: ((string | Date)) | null
  process_start_time?: ((string | Date)) | null
  strokeHistory?: (unknown) | null
  user_id: number
}
export type {FilesFrameSideRel_InsertParameters}
