/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: arnu/EoacKv1V8txp1pYSGKOvMHeH9ImCclYZi4m5tWuSz6g2PhQzKRuCuY4d9+gCON6blOafPp7D4fPFD57IQ==
 */

/* eslint-disable */
// tslint:disable

interface Files {
  ext: string
  filename: (string) | null
  hash: string
  height: (number) | null
  id: number & {readonly __brand?: 'files_id'}
  user_id: number
  width: (number) | null
}
export default Files;

interface Files_InsertParameters {
  ext: string
  filename?: (string) | null
  hash?: string
  height?: (number) | null
  id: number & {readonly __brand?: 'files_id'}
  user_id: number
  width?: (number) | null
}
export type {Files_InsertParameters}
