/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: MkSRWnt9uVBjpEBWmzzcEQqdAvt3p2LAzTczgPh3ztT1/e8sxE56ixMWbaPSq2YA+0HJLAiVzchLE/CQ1BrfFA==
 */

/* eslint-disable */
// tslint:disable

interface FilesHiveRel {
  file_id: number
  hive_id: number
  user_id: number
}
export default FilesHiveRel;

interface FilesHiveRel_InsertParameters {
  file_id: number
  hive_id: number
  user_id: number
}
export type {FilesHiveRel_InsertParameters}
