CREATE TABLE IF NOT EXISTS user_detection_settings (
  user_id BIGINT UNSIGNED NOT NULL,
  sensitivity VARCHAR(16) NOT NULL DEFAULT 'BALANCED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
);
