name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE*'
      - 'CONTRIBUTING.md'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE*'
      - 'CONTRIBUTING.md'
      - '.gitignore'

jobs:
  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - uses: pnpm/action-setup@v4
        with:
          version: 10.29.2

      - uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec jest --config ./test/unit/jest.coverage.json --detectOpenHandles --forceExit --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unit-tests
          name: image-splitter-unit-tests

  integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.5.0
      - uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - uses: pnpm/action-setup@v4
        with:
          version: 10.29.2

      - uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "pnpm"

      - run: just test-integration-ci
